source 'https://rubygems.org'
ruby '2.1.5'
gem 'rails', '4.2.2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'haml'
gem 'konf'
gem 'sass'
gem 'js_stack'
gem 'pg'
gem 'draper'
gem 'bootstrap-sass'
gem 'haml-rails'
gem 'high_voltage'
gem 'simple_form'
gem 'google-analytics-rails'
gem 'newrelic_rpm'
gem 'decent_exposure'
gem 'carrierwave'
gem 'file_validators'
gem 'rack_password'
gem 'capistrano', '~> 3.2.1'
gem 'capistrano-rails'
gem 'capistrano-bundler'
gem 'capistrano-passenger', '0.0.2'
gem 'capistrano-sidekiq' , github: 'seuros/capistrano-sidekiq'
gem 'rvm1-capistrano3', require: false
gem 'whenever', require: false
gem 'roo'
gem 'roo-xls'
gem 'writeexcel'
gem 'mambu', github: 'netguru/mambu-api-ruby'
gem 'sidekiq'
gem 'browser'
gem 'rack-timeout'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_21]
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring-commands-rspec'
end

group :development, :test do
  gem 'byebug'
  gem 'pry-byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'thin'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end
